// <auto-generated />
using System;
using ComAwaPot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComAwaPot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910063036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ComAwaPot.Models.AportacionExtraordinaria", b =>
                {
                    b.Property<int>("AportacionExtraordinariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPorPersona")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasKey("AportacionExtraordinariaId");

                    b.ToTable("AportacionesExtraordinarias");
                });

            modelBuilder.Entity("ComAwaPot.Models.DetallePagoTarifa", b =>
                {
                    b.Property<int>("DetallePagoTarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PagoTarifaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("TEXT");

                    b.Property<int>("TarifaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetallePagoTarifaId");

                    b.HasIndex("PagoTarifaId");

                    b.HasIndex("TarifaId");

                    b.ToTable("DetallesPagoTarifa");
                });

            modelBuilder.Entity("ComAwaPot.Models.HistorialSituacion", b =>
                {
                    b.Property<int>("HistorialSituacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistorialSituacionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("HistorialSituaciones");
                });

            modelBuilder.Entity("ComAwaPot.Models.PagoAportacion", b =>
                {
                    b.Property<int>("PagoAportacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AportacionExtraordinariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagoAportacionId");

                    b.HasIndex("AportacionExtraordinariaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("PagosAportacion");
                });

            modelBuilder.Entity("ComAwaPot.Models.PagoTarifa", b =>
                {
                    b.Property<int>("PagoTarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagoTarifaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("PagosTarifa");
                });

            modelBuilder.Entity("ComAwaPot.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumExt")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId");

                    b.HasIndex("Calle");

                    b.HasIndex("Nombre");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("ComAwaPot.Models.Tarifa", b =>
                {
                    b.Property<int>("TarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("TEXT");

                    b.HasKey("TarifaId");

                    b.HasIndex("Periodo")
                        .IsUnique();

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("ComAwaPot.Models.DetallePagoTarifa", b =>
                {
                    b.HasOne("ComAwaPot.Models.PagoTarifa", "PagoTarifa")
                        .WithMany("Detalles")
                        .HasForeignKey("PagoTarifaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComAwaPot.Models.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("TarifaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PagoTarifa");

                    b.Navigation("Tarifa");
                });

            modelBuilder.Entity("ComAwaPot.Models.HistorialSituacion", b =>
                {
                    b.HasOne("ComAwaPot.Models.Persona", "Persona")
                        .WithMany("HistorialSituaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ComAwaPot.Models.PagoAportacion", b =>
                {
                    b.HasOne("ComAwaPot.Models.AportacionExtraordinaria", "AportacionExtraordinaria")
                        .WithMany("Pagos")
                        .HasForeignKey("AportacionExtraordinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComAwaPot.Models.Persona", "Persona")
                        .WithMany("PagosAportacion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AportacionExtraordinaria");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ComAwaPot.Models.PagoTarifa", b =>
                {
                    b.HasOne("ComAwaPot.Models.Persona", "Persona")
                        .WithMany("PagosTarifa")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ComAwaPot.Models.AportacionExtraordinaria", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ComAwaPot.Models.PagoTarifa", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ComAwaPot.Models.Persona", b =>
                {
                    b.Navigation("HistorialSituaciones");

                    b.Navigation("PagosAportacion");

                    b.Navigation("PagosTarifa");
                });
#pragma warning restore 612, 618
        }
    }
}
